/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-dim': '#e48fec',
        'on-surface-variant': '#adaaaa',
        'outline-variant': '#484847',
        'surface-container-lowest': '#000000',
        'on-background': '#ffffff',
        'primary-container': '#6c9fff',
        'on-secondary': '#460700',
        'on-surface': '#ffffff',
        background: '#0e0e0e',
        tertiary: '#fab0ff',
        surface: '#0e0e0e',
        'surface-variant': '#262626',
        error: '#ff716c',
        'surface-container-highest': '#262626',
        'surface-bright': '#2c2c2c',
        'surface-container-high': '#20201f',
        secondary: '#ff7354',
        'surface-container': '#1a1a1a',
        'secondary-container': '#b72301',
        'inverse-surface': '#fcf9f8',
        'surface-container-low': '#131313',
        'primary-fixed-dim': '#5191ff',
        'on-primary': '#002c65',
        outline: '#767575',
        primary: '#85adff',
        'primary-fixed': '#6c9fff',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
